version: '3'
services:
  pgadmin4:
     image: meedan/pgadmin
     ports:
      - 5050:5050
     volumes:
      - ./sql/.pgadmin:/home/pgadmin/.pgadmin
     environment:
      - PGADMIN_USER=geoportal@proadmintierra.info
      - PGADMIN_PASSWORD=geoportal_user
  database:
    build: .
    ports:
      - 5432:5432
    volumes:
      - ./sql:/scripts_sql
    environment:
      - ALLOW_IP_RANGE="0.0.0.0/0"
      - POSTGRES_USER="geoportal_user"
      - POSTGRES_PASS="geoportal_user"
      - POSTGRES_DBNAME="geoportal"
      - POSTGRES_SCRIPTS="/scripts_sql/geoportal_backup_13_10_2017.backup.sql"
# exec with $ docker-compose up